[package]
name = "convolver"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
fft_convolve_2d = { path = "../" }
clap = "4.5.19"
anyhow = "1.0.89"

[lints.clippy]
needless_return = "allow"
